version: '3.8'

services:
  stan:
    image: nats-streaming:latest
    command: -cid test-cluster
    ports:
      - 8222:8222
      - 4222:4222
    # volumes:
    #   - nats_data:/data

# volumes:
#   nats_data:
#     driver: local
